when:
  - event: push
    branch: Master

# build lol
steps:
  - name: build
    image: picodev:latest
    commands:
      - ls /
      - ls /pico-sdk
      - ls /picotool
      - export PICO_SDK_PATH=/pico-sdk
      - export picotool_DIR=/picotool
      - mkdir build
      - cd build
      - cmake ..
      - make -j4
