when:
  - event: push
    branch: Master

steps:
  - name: build
    image: eptone/pico-build:pico-build
    volumes:
      - ~/PROGRAMS/BFS/Pico/picotool/build:/tools
      - ~/PROGRAMS/Downloaded/Pico/Libs/PicoSDKs:/libs
    commands:
      - ls /
      - ls /libs
      - export PICO_SDK_PATH=/libs/pico-sdk
      - export picotool_DIR=/tools/picotool
      - export PIMORONI_PICO_PATH=/libs/pimoroni-pico
      - mkdir build
      - cd build
      - cmake ..
      - make -j16

