when:
  - event: push
    branch: Master

steps:
  - name: build
    image: pico-build:latest
    commands:
      - mkdir build
      - cd build
      - cmake ..
      - make -j4
    volumes:
      - /Programs/Downloaded/Pico/Libs:/libs
