when:
  - event: push
    branch: Master

steps:
  - name: clone-pico-sdk
    image: alpine/git:v2.47.1
    commands:
      - git clone https://github.com/raspberrypi/pico-sdk.git
      - git clone https://github.com/raspberrypi/picotool.git

  - name: build
    image: alpine
    commands:
      - apk add --no-cache build-base gcc gcc-arm-none-eabi cmake python3 newlib-arm-none-eabi g++-arm-none-eabi binutils-arm-none-eabi >/dev/null
      - cd picotool && mkdir build && cmake -DPICO_SDK_PATH=../../pico-sdk .. && make -j4
      - cd ../..
      - mkdir build
      - cd build
      - cmake -DPICO_SDK_PATH=../pico-sdk -Dpicotool_DIR=../picotool/build/picotool ..
      - make -j4
