when:
  - event: push
    branch: Master

steps:
  - name: build
    image: picodev:latest
    commands:
      - export PICO_SDK_PATH=/pico-sdk
      - export PICOTOOL_FETCH_FROM_GIT_PATH=/picotool
      - mkdir build
      - cd build
      - cmake ..
      - make -j4
