when:
  - event: push
    branch: Master

steps:
  - name: clone-pico-sdk
    image: alpine/git:v2.47.1
    commands:
      - git clone https://github.com/raspberrypi/pico-sdk.git

  - name: build
    image: alpine
    commands:
      - apk add --no-cache build-base gcc cmake >/dev/null
      - mkdir build
      - cd build
      - cmake -DPICO_SDK_PATH=../pico-sdk ..
      - make -j4
