when:
  - event: push
    branch: Master

steps:
  - name: build
    image: pico-build:latest
    commands:
      - export PICO_SDK_PATH=/libs/pico-sdk
      - export picotool_DIR=/libs/picotool
      - export PIMORONI_PICO_PATH=/libs/pimoroni-pico
      - mkdir build
      - cd build
      - cmake ..
      - make -j4
    volumes:
      - /Programs/Downloaded/Pico/Libs:/libs
