when:
  - event: push
    branch: Master

steps:
  - name: build
    image: debain
    commands:
     apt install git cmake
     git clone https://github.com/raspberrypi/pico-sdk.git
     mkdir build
     cd build
     cmake -DPICO-SDK-PATH=../pico-sdk .. && make -j4
